
import { Language, Translation, Course } from './types';

export const LANGUAGES: { code: Language; label: string; dir: 'ltr' | 'rtl' }[] = [
  { code: 'en', label: 'English', dir: 'ltr' },
  { code: 'he', label: 'עברית', dir: 'rtl' },
  { code: 'zh', label: '中文', dir: 'ltr' },
  { code: 'hi', label: 'हिन्दी', dir: 'ltr' },
  { code: 'de', label: 'Deutsch', dir: 'ltr' },
  { code: 'es', label: 'Español', dir: 'ltr' },
  { code: 'fr', label: 'Français', dir: 'ltr' },
];

export const TRANSLATIONS: Record<Language, Translation> = {
  en: {
    title: 'DevLearning Hub',
    subtitle: 'Master JS, TS, Go, Python, Qt, Ruby & Node.js',
    searchPlaceholder: 'Search topics... (Alt+Shift+S)',
    jsTitle: 'JavaScript',
    tsTitle: 'TypeScript',
    goTitle: 'Go (Golang)',
    pyTitle: 'Python',
    qtTitle: 'Qt (PyQt)',
    rbTitle: 'Ruby',
    nodeTitle: 'Node.js',
    jsDesc: 'The language of the web.',
    tsDesc: 'JavaScript with syntax for types.',
    goDesc: 'Simple, reliable, and efficient software.',
    startLearning: 'Start Learning',
    footerRights: 'Noam Gold AI 2026',
    feedback: 'Send Feedback',
    clearInput: 'Clear',
    exportSearch: 'Export',
    offlineMode: 'Offline Ready',
    ttsEnable: 'Speak Text',
    shortcutsInfo: 'Alt+Shift+T: Theme | Alt+Shift+L: Language | Alt+Shift+F: Font | Alt+Shift+S: Search',
    surveyLinkText: 'Check the latest Stack Overflow Developer Survey for trending languages here:',
    copyLabel: 'Copy',
    shareLabel: 'Share',
    exportCodeLabel: 'Export',
    aiExplainLabel: 'AI Explain',
    aiLoadingLabel: 'Thinking...',
    accessibilityTitle: 'Accessibility Statement',
    accessibilityContent: 'We prioritize inclusivity. Features include full keyboard navigation (Alt+Shift shortcuts), ARIA attributes for screen readers, high-contrast dark mode, adjustable font sizes, and a multi-language interface with RTL support.',
    closeLabel: 'Close',
  },
  he: {
    title: 'DevLearning Hub',
    subtitle: 'לימוד JS, TS, Go, Python, Qt, Ruby ו-Node.js',
    searchPlaceholder: 'חיפוש נושאים... (Alt+Shift+S)',
    jsTitle: 'JavaScript',
    tsTitle: 'TypeScript',
    goTitle: 'Go (Golang)',
    pyTitle: 'Python',
    qtTitle: 'Qt (PyQt)',
    rbTitle: 'Ruby',
    nodeTitle: 'Node.js',
    jsDesc: 'השפה של האינטרנט.',
    tsDesc: 'JavaScript עם טיפוסים חזקים.',
    goDesc: 'שפה פשוטה, אמינה ויעילה.',
    startLearning: 'התחל ללמוד',
    footerRights: 'נעם גולד AI 2026',
    feedback: 'שלח משוב',
    clearInput: 'נקה',
    exportSearch: 'ייצוא',
    offlineMode: 'זמין באופליין',
    ttsEnable: 'הקרא טקסט',
    shortcutsInfo: 'Alt+Shift+T: נושא | Alt+Shift+L: שפה | Alt+Shift+F: גופן | Alt+Shift+S: חיפוש',
    surveyLinkText: 'תוכל לראות את הדירוג העדכני של השפות הכי מבוקשות בסקר המפתחים של Stack Overflow כאן:',
    copyLabel: 'העתק',
    shareLabel: 'שתף',
    exportCodeLabel: 'ייצוא',
    aiExplainLabel: 'הסבר AI',
    aiLoadingLabel: 'חושב...',
    accessibilityTitle: 'הצהרת נגישות',
    accessibilityContent: 'אנו שמים דגש על הכללה. תכונות הנגישות כוללות ניווט מקלדת מלא (קיצורי Alt+Shift), תגיות ARIA לקוראי מסך, מצב כהה בניגודיות גבוהה, גדלי גופן ניתנים לשינוי וממשק רב-לשוני עם תמיכה ב-RTL.',
    closeLabel: 'סגור',
  },
  zh: {
    title: 'DevLearning Hub',
    subtitle: '掌握 JS, TS, Go, Python, Qt, Ruby & Node.js',
    searchPlaceholder: '搜索主题... (Alt+Shift+S)',
    jsTitle: 'JavaScript',
    tsTitle: 'TypeScript',
    goTitle: 'Go (Golang)',
    pyTitle: 'Python',
    qtTitle: 'Qt (PyQt)',
    rbTitle: 'Ruby',
    nodeTitle: 'Node.js',
    jsDesc: 'Web语言。',
    tsDesc: '带有类型语法的JavaScript。',
    goDesc: '简单、可靠、高效。',
    startLearning: '开始学习',
    footerRights: 'Noam Gold AI 2026',
    feedback: '发送反馈',
    clearInput: '清除',
    exportSearch: '导出',
    offlineMode: '支持离线',
    ttsEnable: '朗读',
    shortcutsInfo: 'Alt+Shift+T: 主题 | Alt+Shift+L: 语言 | Alt+Shift+F: 字体 | Alt+Shift+S: 搜索',
    surveyLinkText: '在此查看 Stack Overflow 开发者调查中最受欢迎的技术排名：',
    copyLabel: '复制',
    shareLabel: '分享',
    exportCodeLabel: '导出',
    aiExplainLabel: 'AI 解释',
    aiLoadingLabel: '思考中...',
    accessibilityTitle: '辅助功能声明',
    accessibilityContent: '我们优先考虑包容性。 功能包括全键盘导航（Alt+Shift 快捷键）、屏幕阅读器的 ARIA 属性、高对比度深色模式、可调节字体大小以及支持从右到左阅读的多语言界面。',
    closeLabel: '关闭',
  },
  hi: {
    title: 'DevLearning Hub',
    subtitle: 'JS, TS, Go, Python, Qt, Ruby और Node.js सीखें',
    searchPlaceholder: 'विषय खोजें... (Alt+Shift+S)',
    jsTitle: 'JavaScript',
    tsTitle: 'TypeScript',
    goTitle: 'Go (Golang)',
    pyTitle: 'Python',
    qtTitle: 'Qt (PyQt)',
    rbTitle: 'Ruby',
    nodeTitle: 'Node.js',
    jsDesc: 'वेब की भाषा।',
    tsDesc: 'टाइप सिंटैक्स के साथ JavaScript।',
    goDesc: 'सरल, विश्वसनीय और कुशल।',
    startLearning: 'सीखना शुरू करें',
    footerRights: 'नोआम गोल्ड AI 2026',
    feedback: 'प्रतिक्रिया भेजें',
    clearInput: 'साफ करें',
    exportSearch: 'निर्यात',
    offlineMode: 'ऑफलाइन उपलब्ध',
    ttsEnable: 'बोलें',
    shortcutsInfo: 'Alt+Shift+T: थीम | Alt+Shift+L: भाषा | Alt+Shift+F: फ़ॉन्ट | Alt+Shift+S: खोजें',
    surveyLinkText: 'ट्रेंडिंग भाषाओं के लिए नवीनतम स्टैक ओवरफ्लो डेवलपर सर्वेक्षण यहां देखें:',
    copyLabel: 'कॉपी करें',
    shareLabel: 'साझा करें',
    exportCodeLabel: 'निर्यात',
    aiExplainLabel: 'AI स्पष्टीकरण',
    aiLoadingLabel: 'सोच रहा है...',
    accessibilityTitle: 'पहुंच विवरण',
    accessibilityContent: 'हम समावेशिता को प्राथमिकता देते हैं। सुविधाओं में पूर्ण कीबोर्ड नेविगेशन (Alt+Shift शॉर्टकट), स्क्रीन रीडर्स के लिए ARIA गुण, उच्च-विपरीत डार्क मोड, समायोज्य फ़ॉन्ट आकार और RTL समर्थन के साथ बहु-भाषा इंटरफ़ेस शामिल हैं।',
    closeLabel: 'बंद करें',
  },
  de: {
    title: 'DevLearning Hub',
    subtitle: 'Meistern Sie JS, TS, Go, Python, Qt, Ruby & Node.js',
    searchPlaceholder: 'Themen suchen... (Alt+Shift+S)',
    jsTitle: 'JavaScript',
    tsTitle: 'TypeScript',
    goTitle: 'Go (Golang)',
    pyTitle: 'Python',
    qtTitle: 'Qt (PyQt)',
    rbTitle: 'Ruby',
    nodeTitle: 'Node.js',
    jsDesc: 'Die Sprache des Webs.',
    tsDesc: 'JavaScript mit Typen-Syntax.',
    goDesc: 'Einfache, zuverlässige Software.',
    startLearning: 'Lernen starten',
    footerRights: 'Noam Gold AI 2026',
    feedback: 'Feedback senden',
    clearInput: 'Löschen',
    exportSearch: 'Exportieren',
    offlineMode: 'Offline bereit',
    ttsEnable: 'Vorlesen',
    shortcutsInfo: 'Alt+Shift+T: Design | Alt+Shift+L: Sprache | Alt+Shift+F: Schrift | Alt+Shift+S: Suche',
    surveyLinkText: 'Hier finden Sie die aktuelle Stack Overflow-Umfrage zu den beliebtesten Sprachen:',
    copyLabel: 'Kopieren',
    shareLabel: 'Teilen',
    exportCodeLabel: 'Exportieren',
    aiExplainLabel: 'AI Erklären',
    aiLoadingLabel: 'Überlegen...',
    accessibilityTitle: 'Barrierefreiheitserklärung',
    accessibilityContent: 'Wir legen Wert auf Inklusivität. Zu den Funktionen gehören vollständige Tastaturnavigation (Alt+Shift-Shortcuts), ARIA-Attribute für Screenreader, ein kontrastreicher Dunkelmodus, anpassbare Schriftgrößen und eine mehrsprachige Benutzeroberfläche mit RTL-Unterstützung.',
    closeLabel: 'Schließen',
  },
  es: {
    title: 'DevLearning Hub',
    subtitle: 'Domina JS, TS, Go, Python, Qt, Ruby y Node.js',
    searchPlaceholder: 'Buscar temas... (Alt+Shift+S)',
    jsTitle: 'JavaScript',
    tsTitle: 'TypeScript',
    goTitle: 'Go (Golang)',
    pyTitle: 'Python',
    qtTitle: 'Qt (PyQt)',
    rbTitle: 'Ruby',
    nodeTitle: 'Node.js',
    jsDesc: 'El lenguaje de la web.',
    tsDesc: 'JavaScript con sintaxis de tipos.',
    goDesc: 'Software simple y eficiente.',
    startLearning: 'Empezar a aprender',
    footerRights: 'Noam Gold AI 2026',
    feedback: 'Enviar comentarios',
    clearInput: 'Limpiar',
    exportSearch: 'Exportar',
    offlineMode: 'Listo para offline',
    ttsEnable: 'Escuchar',
    shortcutsInfo: 'Alt+Shift+T: Tema | Alt+Shift+L: Idioma | Alt+Shift+F: Fuente | Alt+Shift+S: Buscar',
    surveyLinkText: 'Consulta la última encuesta de desarrolladores de Stack Overflow aquí:',
    copyLabel: 'Copiar',
    shareLabel: 'Compartir',
    exportCodeLabel: 'Exportar',
    aiExplainLabel: 'AI Explicar',
    aiLoadingLabel: 'Pensando...',
    accessibilityTitle: 'Declaración de accesibilidad',
    accessibilityContent: 'Priorizamos la inclusión. Las características incluyen navegación completa por teclado (atajos Alt+Shift), atributos ARIA para lectores de pantalla, modo oscuro de alto contraste, tamaños de fuente ajustables y una interfaz en varios idiomas con soporte RTL.',
    closeLabel: 'Cerrar',
  },
  fr: {
    title: 'DevLearning Hub',
    subtitle: 'Maîtrisez JS, TS, Go, Python, Qt, Ruby & Node.js',
    searchPlaceholder: 'Rechercher... (Alt+Shift+S)',
    jsTitle: 'JavaScript',
    tsTitle: 'TypeScript',
    goTitle: 'Go (Golang)',
    pyTitle: 'Python',
    qtTitle: 'Qt (PyQt)',
    rbTitle: 'Ruby',
    nodeTitle: 'Node.js',
    jsDesc: 'Le langage du web.',
    tsDesc: 'JavaScript avec types.',
    goDesc: 'Logiciel simple et efficace.',
    startLearning: 'Commencer',
    footerRights: 'Noam Gold AI 2026',
    feedback: 'Envoyer un avis',
    clearInput: 'Effacer',
    exportSearch: 'Exporter',
    offlineMode: 'Mode hors-ligne',
    ttsEnable: 'Écouter',
    shortcutsInfo: 'Alt+Shift+T: Thème | Alt+Shift+L: Langue | Alt+Shift+F: Police | Alt+Shift+S: Rechercher',
    surveyLinkText: 'Consultez la dernière enquête Stack Overflow sur les technologies ici :',
    copyLabel: 'Copier',
    shareLabel: 'Partager',
    exportCodeLabel: 'Exporter',
    aiExplainLabel: 'AI Expliquer',
    aiLoadingLabel: 'Réflexion...',
    accessibilityTitle: 'Déclaration d\'accessibilité',
    accessibilityContent: 'Nous accordons la priorité à l\'inclusivité. Les fonctionnalités incluent une navigation complète au clavier (raccourcis Alt+Shift), des attributs ARIA pour les lecteurs d\'écran, un mode sombre à contraste élevé, des tailles de police réglables et une interface multilingue avec prise en charge RTL.',
    closeLabel: 'Fermer',
  }
};

export const COURSES: Course[] = [
  {
    id: 'js-1',
    title: 'JavaScript Deep Dive',
    category: 'JS',
    modules: [
      { id: 'js-m1', title: 'Closure', description: 'Functions bundled with lexical environment.', code: 'function outer() {\n  let count = 0;\n  return () => ++count;\n}' },
      { id: 'js-m2', title: 'Destructuring', description: 'Unpacking values from arrays or properties.', code: 'const { name, age } = user;\nconst [first, ...rest] = items;' },
      { id: 'js-m3', title: 'Event Loop', description: 'Non-blocking I/O model execution.', code: 'console.log("Start");\nsetTimeout(() => console.log("Timer"), 0);\nconsole.log("End");' }
    ]
  },
  {
    id: 'node-1',
    title: 'Node.js Essentials',
    category: 'NODE',
    modules: [
      { id: 'node-m1', title: 'FS Module', description: 'Interact with the file system.', code: 'const fs = require("fs");\nfs.writeFileSync("test.txt", "Hello World");' },
      { id: 'node-m2', title: 'HTTP Server', description: 'Create a web server without frameworks.', code: 'const http = require("http");\nhttp.createServer((req, res) => {\n  res.end("Hello!");\n}).listen(3000);' },
      { id: 'node-m3', title: 'Buffer', description: 'Handling binary data streams.', code: 'const buf = Buffer.from("NodeJS");\nconsole.log(buf.toString("hex"));' }
    ]
  },
  {
    id: 'ts-1',
    title: 'TypeScript Advanced',
    category: 'TS',
    modules: [
      { id: 'ts-m1', title: 'Mapped Types', description: 'Creating new types based on old ones.', code: 'type Readonly<T> = {\n  readonly [P in keyof T]: T[P];\n};' },
      { id: 'ts-m2', title: 'Conditional Types', description: 'Type selection based on relations.', code: 'type IsString<T> = T extends string ? true : false;' },
      { id: 'ts-m3', title: 'Utility Types', description: 'Built-in transformations.', code: 'type PartialUser = Partial<User>;\ntype NameOnly = Pick<User, "name">;' }
    ]
  },
  {
    id: 'go-1',
    title: 'Go Systems Programming',
    category: 'GO',
    modules: [
      { id: 'go-m1', title: 'Channels', description: 'Pipes that connect concurrent goroutines.', code: 'ch := make(chan string)\ngo func() { ch <- "ping" }()\nfmt.Println(<-ch)' },
      { id: 'go-m2', title: 'Interfaces', description: 'Duck typing in a static language.', code: 'type Reader interface {\n  Read(p []byte) (n int, err error)\n}' },
      { id: 'go-m3', title: 'Defer', description: 'Delay execution until function returns.', code: 'f, _ := os.Open("file.txt")\ndefer f.Close()' }
    ]
  },
  {
    id: 'py-1',
    title: 'Python Mastery',
    category: 'PY',
    modules: [
      { id: 'py-m1', title: 'Generators', description: 'Memory-efficient iterations.', code: 'def countdown(n):\n  while n > 0:\n    yield n\n    n -= 1' },
      { id: 'py-m2', title: 'Context Managers', description: 'Resource management with "with".', code: 'with open("test.txt") as f:\n  data = f.read()' },
      { id: 'py-m3', title: 'Metaclasses', description: 'Classes that create classes.', code: 'class MyMeta(type):\n  def __new__(cls, name, bases, dct):\n    return super().__new__(cls, name, bases, dct)' }
    ]
  },
  {
    id: 'qt-1',
    title: 'Qt Application Design',
    category: 'QT',
    modules: [
      { id: 'qt-m1', title: 'Layout Management', description: 'Automatic widget positioning.', code: 'layout = QVBoxLayout()\nlayout.addWidget(QPushButton("Click"))\nself.setLayout(layout)' },
      { id: 'qt-m2', title: 'Custom Styles', description: 'Styling with QSS (Qt Style Sheets).', code: 'widget.setStyleSheet("background-color: #333; color: white;")' },
      { id: 'qt-m3', title: 'Threading', description: 'Running heavy tasks in background.', code: 'self.worker = WorkerThread()\nself.worker.started.connect(self.on_start)' }
    ]
  },
  {
    id: 'rb-1',
    title: 'Ruby Advanced Scripting',
    category: 'RB',
    modules: [
      { id: 'rb-m1', title: 'Metaprogramming', description: 'Code that writes code.', code: 'class MyClass\n  define_method(:greet) { puts "Hello!" }\nend' },
      { id: 'rb-m2', title: 'Enumerable', description: 'Powerful collection manipulation.', code: 'words.group_by(&:length)\nnumbers.select(&:even?).map { |n| n * 2 }' },
      { id: 'rb-m3', title: 'Symbols', description: 'Immutable, reusable string identifiers.', code: 'options = { :draft => true, :color => :red }' }
    ]
  }
];
